general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/ecosystem/hyprlock.conf
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 3
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 20
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
