-- Generated by dotfiles-apply-theme from shared/.config/dotfiles/theme.json
return {
    name = "Ethereal",
    font_family = "Hack Nerd Font",
    colors = {
        accent = "#7d82d9",
        background = "#060B1E",
        surface = "#3C486D",
        foreground = "#ffcead",
        cursor = "#ffcead",
        selection_background = "#ffcead",
        selection_foreground = "#060B1E",
        critical = "#ED5B5A",
        success = "#92a593",
        warning = "#E9BB4F",
        orange = "#F99957",
        purple = "#c89dc1",
        cyan = "#a3bfd1",
        muted = "#6d7db6",
    },
    hypr = {
        accent = "rgba(7d82d9ee)",
        surface = "rgba(3C486Daa)",
        background = "rgba(060B1Eee)",
        shadow = "rgba(060B1E99)",
        critical = "rgba(ED5B5Aee)",
    },
}
