[main]
font = Hack Nerd Font Mono:size=11:line-height=16px
pad = 12x12

# Gruvbox

[colors]
background=282828
foreground=ebdbb2
regular0=282828
regular1=cc241d
regular2=98971a
regular3=d79921
regular4=458588
regular5=b16286
regular6=689d6a
regular7=a89984
bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ebdbb2


#[colors]
#foreground = cad3f5
#background = 24273a
## Normal/regular colors (color palette 0-7)
## the colors used here are catppucin macchiato
#regular0=494d64
#regular1=ed8796
#regular2=a6da95
#regular3=eed49f
#regular4=8aadf4
#regular5=f5bde6
#regular6=8bd5ca
#regular7=b8c0e0

#bright0=5b6078
#bright1=ed8796
#bright2=a6da95
#bright3=eed49f
#bright4=8aadf4
#bright5=f5bde6
#bright6=8bd5ca
#bright7=a5adcb
