-- Generated by dotfiles-apply-theme from everforest.json
return {
    name = "Everforest",
    font_family = "Hack Nerd Font",
    colors = {
        accent = "#7fbbb3",
        background = "#2d353b",
        surface = "#475258",
        foreground = "#d3c6aa",
        cursor = "#d3c6aa",
        selection_background = "#d3c6aa",
        selection_foreground = "#2d353b",
        critical = "#e67e80",
        success = "#a7c080",
        warning = "#dbbc7f",
        orange = "#d3c6aa",
        purple = "#d699b6",
        cyan = "#83c092",
        muted = "#475258",
    },
    hypr = {
        accent = "rgba(7fbbb3ee)",
        surface = "rgba(475258aa)",
        background = "rgba(2d353bee)",
        shadow = "rgba(2d353b99)",
        critical = "rgba(e67e80ee)",
    },
}
